/* GENERATED by scripts/gen-imports.mjs — do not edit.
   Regenerated on every build; see the comment in that file for why the
   imports are static rather than globbed. */
import type { ComponentType } from 'react';

import C_bullet_chart from '../../components-src/bullet-chart/Component.tsx';
import C_code_input from '../../components-src/code-input/Component.tsx';
import C_command_button from '../../components-src/command-button/Component.tsx';
import C_copy_receipt from '../../components-src/copy-receipt/Component.tsx';
import C_difference_header from '../../components-src/difference-header/Component.tsx';
import C_duration_field from '../../components-src/duration-field/Component.tsx';
import C_fold_reveal_section from '../../components-src/fold-reveal-section/Component.tsx';
import C_grapheme_budget_field from '../../components-src/grapheme-budget-field/Component.tsx';
import C_marching_ants from '../../components-src/marching-ants/Component.tsx';
import C_odometer_stat from '../../components-src/odometer-stat/Component.tsx';
import C_optimistic_row from '../../components-src/optimistic-row/Component.tsx';
import C_progressive_blur_sheet from '../../components-src/progressive-blur-sheet/Component.tsx';
import C_queue_position from '../../components-src/queue-position/Component.tsx';
import C_scroll_filmstrip from '../../components-src/scroll-filmstrip/Component.tsx';
import C_segment_nav from '../../components-src/segment-nav/Component.tsx';
import C_shortcut_recorder from '../../components-src/shortcut-recorder/Component.tsx';
import C_slide_confirm from '../../components-src/slide-confirm/Component.tsx';
import C_spotlight_card from '../../components-src/spotlight-card/Component.tsx';
import C_staged_pipeline from '../../components-src/staged-pipeline/Component.tsx';
import C_unit_field from '../../components-src/unit-field/Component.tsx';
import C_weight_shift_button from '../../components-src/weight-shift-button/Component.tsx';

export const components: Record<string, ComponentType> = {
  "bullet-chart": C_bullet_chart,
  "code-input": C_code_input,
  "command-button": C_command_button,
  "copy-receipt": C_copy_receipt,
  "difference-header": C_difference_header,
  "duration-field": C_duration_field,
  "fold-reveal-section": C_fold_reveal_section,
  "grapheme-budget-field": C_grapheme_budget_field,
  "marching-ants": C_marching_ants,
  "odometer-stat": C_odometer_stat,
  "optimistic-row": C_optimistic_row,
  "progressive-blur-sheet": C_progressive_blur_sheet,
  "queue-position": C_queue_position,
  "scroll-filmstrip": C_scroll_filmstrip,
  "segment-nav": C_segment_nav,
  "shortcut-recorder": C_shortcut_recorder,
  "slide-confirm": C_slide_confirm,
  "spotlight-card": C_spotlight_card,
  "staged-pipeline": C_staged_pipeline,
  "unit-field": C_unit_field,
  "weight-shift-button": C_weight_shift_button,
};
