/* GENERATED by scripts/gen-imports.mjs — do not edit.
   Regenerated on every build; see the comment in that file for why the
   imports are static rather than globbed. */
import type { ComponentType } from 'react';

import C_adjust_last_action from '../../components-src/adjust-last-action/Component.tsx';
import C_bertin_matrix from '../../components-src/bertin-matrix/Component.tsx';
import C_bidi_comment_card from '../../components-src/bidi-comment-card/Component.tsx';
import C_bullet_chart from '../../components-src/bullet-chart/Component.tsx';
import C_challenge_response_checklist from '../../components-src/challenge-response-checklist/Component.tsx';
import C_code_input from '../../components-src/code-input/Component.tsx';
import C_collation_sort_table from '../../components-src/collation-sort-table/Component.tsx';
import C_command_button from '../../components-src/command-button/Component.tsx';
import C_constraint_solver_form from '../../components-src/constraint-solver-form/Component.tsx';
import C_convergence_trace from '../../components-src/convergence-trace/Component.tsx';
import C_copy_receipt from '../../components-src/copy-receipt/Component.tsx';
import C_country_address_form from '../../components-src/country-address-form/Component.tsx';
import C_difference_header from '../../components-src/difference-header/Component.tsx';
import C_duration_field from '../../components-src/duration-field/Component.tsx';
import C_endless_ledger from '../../components-src/endless-ledger/Component.tsx';
import C_fold_reveal_section from '../../components-src/fold-reveal-section/Component.tsx';
import C_forced_colors_chart from '../../components-src/forced-colors-chart/Component.tsx';
import C_grapheme_budget_field from '../../components-src/grapheme-budget-field/Component.tsx';
import C_ime_search_field from '../../components-src/ime-search-field/Component.tsx';
import C_infinite_drag_field from '../../components-src/infinite-drag-field/Component.tsx';
import C_localized_progress_loader from '../../components-src/localized-progress-loader/Component.tsx';
import C_magic_plus_drag from '../../components-src/magic-plus-drag/Component.tsx';
import C_marching_ants from '../../components-src/marching-ants/Component.tsx';
import C_multiscript_text_column from '../../components-src/multiscript-text-column/Component.tsx';
import C_odometer_stat from '../../components-src/odometer-stat/Component.tsx';
import C_optimistic_row from '../../components-src/optimistic-row/Component.tsx';
import C_origin_morph_dialog from '../../components-src/origin-morph-dialog/Component.tsx';
import C_outlier_heatmap from '../../components-src/outlier-heatmap/Component.tsx';
import C_peel_corner_card from '../../components-src/peel-corner-card/Component.tsx';
import C_pressure_signature_pad from '../../components-src/pressure-signature-pad/Component.tsx';
import C_priority_overflow_toolbar from '../../components-src/priority-overflow-toolbar/Component.tsx';
import C_progressive_blur_sheet from '../../components-src/progressive-blur-sheet/Component.tsx';
import C_quantile_dots from '../../components-src/quantile-dots/Component.tsx';
import C_queue_position from '../../components-src/queue-position/Component.tsx';
import C_safe_triangle_hover from '../../components-src/safe-triangle-hover/Component.tsx';
import C_scroll_condense_wordmark from '../../components-src/scroll-condense-wordmark/Component.tsx';
import C_scroll_filmstrip from '../../components-src/scroll-filmstrip/Component.tsx';
import C_segment_nav from '../../components-src/segment-nav/Component.tsx';
import C_segmented_cache_bar from '../../components-src/segmented-cache-bar/Component.tsx';
import C_shared_field_steps from '../../components-src/shared-field-steps/Component.tsx';
import C_shortcut_recorder from '../../components-src/shortcut-recorder/Component.tsx';
import C_slide_confirm from '../../components-src/slide-confirm/Component.tsx';
import C_sliding_pane_stack from '../../components-src/sliding-pane-stack/Component.tsx';
import C_sort_morph_table from '../../components-src/sort-morph-table/Component.tsx';
import C_spotlight_card from '../../components-src/spotlight-card/Component.tsx';
import C_staged_pipeline from '../../components-src/staged-pipeline/Component.tsx';
import C_switch_scanning_menu from '../../components-src/switch-scanning-menu/Component.tsx';
import C_tear_off_panel from '../../components-src/tear-off-panel/Component.tsx';
import C_unit_field from '../../components-src/unit-field/Component.tsx';
import C_weight_shift_button from '../../components-src/weight-shift-button/Component.tsx';
import C_zone_overlap_ribbon from '../../components-src/zone-overlap-ribbon/Component.tsx';

export const components: Record<string, ComponentType> = {
  "adjust-last-action": C_adjust_last_action,
  "bertin-matrix": C_bertin_matrix,
  "bidi-comment-card": C_bidi_comment_card,
  "bullet-chart": C_bullet_chart,
  "challenge-response-checklist": C_challenge_response_checklist,
  "code-input": C_code_input,
  "collation-sort-table": C_collation_sort_table,
  "command-button": C_command_button,
  "constraint-solver-form": C_constraint_solver_form,
  "convergence-trace": C_convergence_trace,
  "copy-receipt": C_copy_receipt,
  "country-address-form": C_country_address_form,
  "difference-header": C_difference_header,
  "duration-field": C_duration_field,
  "endless-ledger": C_endless_ledger,
  "fold-reveal-section": C_fold_reveal_section,
  "forced-colors-chart": C_forced_colors_chart,
  "grapheme-budget-field": C_grapheme_budget_field,
  "ime-search-field": C_ime_search_field,
  "infinite-drag-field": C_infinite_drag_field,
  "localized-progress-loader": C_localized_progress_loader,
  "magic-plus-drag": C_magic_plus_drag,
  "marching-ants": C_marching_ants,
  "multiscript-text-column": C_multiscript_text_column,
  "odometer-stat": C_odometer_stat,
  "optimistic-row": C_optimistic_row,
  "origin-morph-dialog": C_origin_morph_dialog,
  "outlier-heatmap": C_outlier_heatmap,
  "peel-corner-card": C_peel_corner_card,
  "pressure-signature-pad": C_pressure_signature_pad,
  "priority-overflow-toolbar": C_priority_overflow_toolbar,
  "progressive-blur-sheet": C_progressive_blur_sheet,
  "quantile-dots": C_quantile_dots,
  "queue-position": C_queue_position,
  "safe-triangle-hover": C_safe_triangle_hover,
  "scroll-condense-wordmark": C_scroll_condense_wordmark,
  "scroll-filmstrip": C_scroll_filmstrip,
  "segment-nav": C_segment_nav,
  "segmented-cache-bar": C_segmented_cache_bar,
  "shared-field-steps": C_shared_field_steps,
  "shortcut-recorder": C_shortcut_recorder,
  "slide-confirm": C_slide_confirm,
  "sliding-pane-stack": C_sliding_pane_stack,
  "sort-morph-table": C_sort_morph_table,
  "spotlight-card": C_spotlight_card,
  "staged-pipeline": C_staged_pipeline,
  "switch-scanning-menu": C_switch_scanning_menu,
  "tear-off-panel": C_tear_off_panel,
  "unit-field": C_unit_field,
  "weight-shift-button": C_weight_shift_button,
  "zone-overlap-ribbon": C_zone_overlap_ribbon,
};
