/* Astro resolves a component's renderer from the import statement, so a
   component pulled in through import.meta.glob renders with no renderer and
   fails with NoMatchingImport. Static imports keep the association, which also
   means the previews server-render and then hydrate rather than popping in. */
import { readdirSync, existsSync, writeFileSync, readFileSync } from 'node:fs';
import { join } from 'node:path';

const SRC = 'components-src';
const slugs = readdirSync(SRC)
  .filter((d) => !d.startsWith('_') && existsSync(join(SRC, d, 'Component.tsx')))
  .sort();

const ident = (s) => 'C_' + s.replace(/[^a-zA-Z0-9]/g, '_');

/* Astro's compiler resolves a client directive's renderer from the IDENTIFIER
   written in the JSX. A component reached through a lookup table has no
   identifier to resolve, which is the NoMatchingImport error — so the host is
   generated as one direct reference per component rather than a map. */
const host = [
  '---',
  '/* GENERATED by scripts/gen-imports.mjs — do not edit. */',
  ...slugs.map((s) => `import ${ident(s)} from '../../components-src/${s}/Component.tsx';`),
  'const { slug } = Astro.props as { slug: string };',
  '---',
  ...slugs.map((s) => `{slug === ${JSON.stringify(s)} && <${ident(s)} client:only="react" />}`),
  '',
].join('\n');
writeFileSync('src/components/ComponentHost.astro', host);

const out = [
  '/* GENERATED by scripts/gen-imports.mjs — do not edit.',
  '   Regenerated on every build; see the comment in that file for why the',
  '   imports are static rather than globbed. */',
  "import type { ComponentType } from 'react';",
  '',
  ...slugs.map((s) => `import ${ident(s)} from '../../components-src/${s}/Component.tsx';`),
  '',
  'export const components: Record<string, ComponentType> = {',
  ...slugs.map((s) => `  ${JSON.stringify(s)}: ${ident(s)},`),
  '};',
  '',
];

const path = 'src/lib/components.generated.ts';
const next = out.join('\n');
const prev = existsSync(path) ? readFileSync(path, 'utf8') : '';
if (prev !== next) writeFileSync(path, next);
console.log(`gen-imports: ${slugs.length} React component${slugs.length === 1 ? '' : 's'}`);
